version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable  # Base image with Docker CLI
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/yt-tools-ui:latest .

      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Tag and push Docker image
          command: |
            docker tag $DOCKERHUB_USERNAME/yt-tools-ui:latest $DOCKERHUB_USERNAME/yt-tools-ui:${CIRCLE_SHA1}
            docker push $DOCKERHUB_USERNAME/yt-tools-ui:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build-and-push:
          context: docker
          filters:
            branches:
              only: deploy
